[project]
name = "deepsearch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "google-search-results>=2.4.2",
    "ipykernel>=6.30.1",
    "openai-agents>=0.2.10",
    "tavily-python>=0.7.11",
]
